---
title: "1. Assignment Macro II"
author: "Hannes Wilkovits, Gustav Pirich"
date: "`r Sys.Date()`"
output: pdf_document
---
#Question 1
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

```{r}
# Reading the contents of TSV file using read_tsv() method
setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Wirtschaftsuniversität/MASTER/Adv.MacroII/Data")
namq_10_gdp__custom_5705993_tabular <- readr::read_tsv("namq_10_gdp__custom_5705993_tabular.tsv")
```


```{r}
names(namq_10_gdp__custom_5705993_tabular)[1] <- "rows"

namq_10_gdp__custom_5705993_tabular_t <- t(namq_10_gdp__custom_5705993_tabular)

namq_10_gdp__custom_5705993_tabular.tsv_t_df <- as.data.frame(namq_10_gdp__custom_5705993_tabular_t)

names(namq_10_gdp__custom_5705993_tabular.tsv_t_df)[1] <- "Date"
names(namq_10_gdp__custom_5705993_tabular.tsv_t_df)[2] <- "Y"
names(namq_10_gdp__custom_5705993_tabular.tsv_t_df)[3] <- "C"
names(namq_10_gdp__custom_5705993_tabular.tsv_t_df)[4] <- "G"
names(namq_10_gdp__custom_5705993_tabular.tsv_t_df)[5] <- "I"

table <- namq_10_gdp__custom_5705993_tabular.tsv_t_df[-1,]

table_2 <- table %>%
  filter(Date >	"1996-Q1")

table_2$Y <- gsub("p","",as.character(table_2$Y))
table_2$C <- gsub("p","",as.character(table_2$C))
table_2$I <- gsub("p","",as.character(table_2$I))
table_2$G <- gsub("p","",as.character(table_2$G))

final_data <- table_2 %>% mutate(across(.cols = c("Y", "C", "G", "I"), as.numeric))
```

